### ISSUE TITLE
Workshop Tasks: Process Battle

### ISSUE THREAD

**Issue by TheKeithStewart** [TheKeithStewart/tour-of-heroes#26]
- [x] Write steps 

# Task 1: Determine Winner of Battle
**Description:**
Upon clicking on the "Battle" button the dance battle begins. The winner is determined by executing the DancerService.determineBattleWinnerByCategory() function.

**Tests:**
- [x] Dance battle is processed

# Task 2: Error Handler

- [x] There is an error and the dance battle fails

# Task 3: Add Delay
**Description:**

**Tests:**
- [x] Update tests to work with delay
