### ISSUE TITLE
Task 4

### ISSUE THREAD

**Issue by TheKeithStewart** [TheKeithStewart/tour-of-heroes#28]
# Task 4 (optional): Tie Break
**Description**

**Tests:**
- [ ] If category wins are not tied then do not use total ratings to determine winner
- [ ] If category wins are tied then determine winner based on total ratings
- [ ] If total ratings are still a tie then randomly choose a winner
